dataset: monkey

path:
  origin_path: "./dataset/monkey"  # set to the root directory of dataset
  preprocessed_path: "./dataset/preprocessed/monkey/set_by_class_length"  # set to the directory 
  dataset_summary: "./dataset/preprocessed/"

preprocessing:
  segment_size: 256 # each sample length
  chunk_size: 32 # 16 first only class

