model_name: 'DisentangledVAE1D'

DisentangledVAE1D:
  f_dim: 256
  z_dim: 32
  conv_dim: 1024 # 2048
  step: 256
  in_size: 64
  hidden_dim: 512
  mel_dim: 80
  nonlinearity: None
  factorised: True
  shuffle_input: True

static_encoder:
  in_channels: 80 # n_mel_channels
  h_channels: 256
  out_channels: 256 # f dim & individual embedding
  conv_kernels: [3, 3, 5] # [3, 3, 5, 5]
  paddings: [1, 1, 2] # [1, 1, 2, 2]
  pooling_kernels: [2, 2, 2] # [2, 2, 2, 2]
  pooling_type: 'mean'
  activation: 'relu'
