path:
  save_path: "output/checkpoint"
  log_path: "output/log"
  result_path: "output/result"

load_model: False
# load_model: True
load_step: 0

optimizer:
  batch_size: 64
  learning_rate: 0.0001
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: []
  anneal_rate: 1.0
  con_gamma: 100.
  indi_gamma: 10.
  con_mi: 1.3
  indi_mi: 60.

step:
  total_step: 80000
  mi_stop: 20000
  log_step: 500
  val_step: 5000
  save_step: 50000

# step:
#   total_step: 200000
#   mi_stop: 20000
#   log_step: 500
#   val_step: 5000
#   save_step: 50000

misc:
  seed: 114514
