path:
  save_path: "checkpoint"
  log_path: "log"
  result_path: "result"

# load_model: False
# load_step: 0
# start_epoch: 0

load_model: True
load_step: 100000
start_epoch: 0


optimizer:
  batch_size: 32
  learning_rate: 0.0002 # 0.0001
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: []
  anneal_rate: 1.0
  
  con_gamma: 100.
  indi_gamma: 10.
  con_mi: 1.3
  indi_mi: 60.

step:
  total_step: 200000
  mi_stop: 20000
  log_step: 200
  val_step: 500
  save_step: 1000
  total_epoch: 800


misc:
  seed: 114514
