path:
  save_path: "checkpoint"
  log_path: "log"
  result_path: "result"

load_model: False
load_step: 0
# load_model: True
# load_step: 80000

optimizer:
  batch_size: 48
  learning_rate: 0.0001
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: []
  anneal_rate: 1.0
  con_gamma: 100. # 100.
  con_mi: 0.8 # 1.3
  indi_gamma: 1. # 10.
  indi_mi: 40. # 60.

step:
  total_step: 100000
  mi_stop: 30000 #20000
  log_step: 500
  val_step: 2000
  save_step: 5000


misc:
  seed: 114514
