dataset: great_bird

path:
  corpus_path: "/mnt/work/dataset/vctk"  # set to the root directory of the unzipped VCTK
  preprocessed_path: "/mnt/work/dataset/preprocessed/great_bird/data_info_smaller"  # set to the directory to hold the features of VCTK
  dataset_summary: "/mnt/work/dataset/preprocessed/great_bird/data_info_smaller/data_info_caller.json"


preprocessing:
  n_val_spk: 10
  n_test_spk: 10
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder set to null for MelGAN vocoder
  mel_hg:
    num_mels: 80
    num_freq: 1025
    n_fft: 1024
    hop_size: 256
    win_size: 1024
    sampling_rate: 22050
    fmin: 0
    fmax: 8000
  sil_top_db: 30.

  segment_size: 300 # 256
  chunk_size: 30 # 32

  n_pitch_bins: 8
  n_energy_bins: 8
