model_name: 'VAEbase_one_static'

prior:
  indi_dim: 128
  con_dim: 128

static_encoder:
  in_channels: 80 # n_mel_channels
  h_channels: 256
  out_channels: 128 # individual embedding
  conv_kernels: [3, 3, 5] # [3, 3, 5, 5]
  paddings: [1, 1, 2] # [1, 1, 2, 2]
  pooling_kernels: [2, 2, 2] # [2, 2, 2, 2]
  pooling_type: 'mean'
  activation: 'relu'

decoder:
  in_channels: 128 # indi_dim + con_dim
  h_channels: 256
  out_channels: 80 # con_dim
  conv_kernels: [3, 3]
  paddings: [1, 1]
  activation: 'relu'
  sa_layer: 2
  sa_head: 2
  sa_hidden: 256
  sa_filter_size: 1024
  sa_kernel_size: [9, 1]
  sa_dropout: 0.2
  max_seq_len: 2048 # transformer setting


