model_name: 'VAEbase_one'

prior:
  indi_dim: 128
  con_dim: 128

dynamic_encoder:
  in_channels: 80 # n_mel_channels
  h_channels: 256
  out_channels: 1 # 128 # content embedding
  conv_kernels: [3, 3]
  paddings: [1, 1]
  activation: 'relu'
  sa_layer: 2
  sa_head: 2
  sa_hidden: 256
  sa_filter_size: 1024
  sa_kernel_size: [9, 1]
  sa_dropout: 0.2
  max_seq_len: 2048 # transformer setting

decoder:
  in_channels: 1 
  h_channels: 256
  out_channels: 80 
  conv_kernels: [3, 3]
  paddings: [1, 1]
  activation: 'relu'
  sa_layer: 2
  sa_head: 2
  sa_hidden: 256
  sa_filter_size: 1024
  sa_kernel_size: [9, 1]
  sa_dropout: 0.2
  max_seq_len: 2048 # transformer setting

