path:
  save_path: "checkpoint"
  log_path: "log"
  result_path: "result"

load_model: False
# load_model: True
# load_step: 65000

optimizer:
  batch_size: 48
  learning_rate: 0.00012 # 0.0001
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: []
  anneal_rate: 1.0

  con_gamma: 100.
  con_mi: 1.5 # 1.3

  indi_gamma: 40.
  indi_mi: 80.0 # 60.

step:
  total_step: 200000
  mi_stop: 80000 # 
  log_step: 500
  val_step: 500
  save_step: 5000

misc:
  seed: 114514
